using UnityEngine;
using System.Collections;

public enum TileItemMoveType {
	DOWN, OFFSET, MIX, HERO_DROP, GENERATED_TILEITEM_DROP, EATER, HERO_SKILL,
	BUY_USERASSET, AWARDTILEITEM_1, AWARDTILEITEM_2
}
