using UnityEngine;
using System.Collections;

public enum TileItemMoveType {
	DOWN, OFFSET, MIX, HERO_DROP, GENERATED_TILEITEM_DROP, EATER, HERO_SKILL

}

public enum UIMoveType {
	BUY_USERASSET, AWARDTILEITEM_1, AWARDTILEITEM_2, AWARD_EXPERIENCE_1, AWARD_EXPERIENCE_2,
	FAILURE_AWARD_1, FAILURE_AWARD_2
}
	


